apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ template "fullname" . }}-zabbix-web
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    tier: zabbix-web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}-zabbix-web
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: {{ template "fullname" . }}-zabbix-web
          image: zabbix/zabbix-web-nginx-mysql:alpine-3.4-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: {{ template "fullname" . }}-web-http
          - containerPort: 443
            name: {{ template "fullname" . }}-web-https
          resources:
           limits:
            cpu: 200m
            memory: 400Mi
           requests:
            cpu: 200m
            memory: 400Mi
          livenessProbe:
            httpGet:
              path: /
              port: {{ template "fullname" . }}-web-http
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: {{ template "fullname" . }}-web-http
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          env:
          - name: ZBX_SERVER_NAME
            value: "Zabbix kubernetes"
          - name: PHP_TZ
            value: "Europe/Riga"
          - name: MYSQL_USER
            valueFrom:
             secretKeyRef:
              name: {{ template "fullname" . }}-db-secret
              key: {{ template "fullname" . }}-db-zbx-user
          - name: MYSQL_PASSWORD
            valueFrom:
             secretKeyRef:
              name: {{ template "fullname" . }}-db-secret
              key: {{ template "fullname" . }}-db-zbx-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
              name: {{ template "fullname" . }}-db-secret
              key: {{ template "fullname" . }}-db-root-pass
          - name: MYSQL_DATABASE
            value: "zabbix"
          volumeMounts:
          - name: {{ template "fullname" . }}-zabbix-web-ssl
            mountPath: /etc/ssl/nginx
            readOnly: true
      volumes:
       - hostPath:
          path: /home/dotneft/zbx/zbx_env/etc/ssl/nginx/
         name: {{ template "fullname" . }}-zabbix-web-ssl
