kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-zabbix-mysql-data
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
