apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}-zabbix-agent
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    tier: agent
spec:
  updateStrategy:
   type: RollingUpdate
   rollingUpdate:
    maxUnavailable: 1
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}-zabbix-agent
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: {{ template "fullname" . }}-zabbix-agent
          image: zabbix/zabbix-agent:alpine-3.4-latest
          imagePullPolicy: Always
          resources:
           limits:
            cpu: 100m
            memory: 54Mi
           requests:
            cpu: 100m
            memory: 54Mi
          ports:
          - containerPort: 10050
            name: {{ template "fullname" . }}-zabbix-agent
          env:
          - name: ZBX_SERVER_HOST
            value: "zabbix-server"
          - name: ZBX_PASSIVE_ALLOW
            value: "true"
          - name: ZBX_STARTAGENTS
            value: "3"
          - name: ZBX_TIMEOUT
            value: "10"
          securityContext:
            privileged: true
