apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-zabbix-proxy-mysql
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
  - port: 10051
    targetPort: 10051
    name: {{ template "fullname" . }}-zabbix-trapper
  - port: 162
    targetPort: 162
    protocol: UDP
    name: snmp-trap
  selector:
    name: {{ template "fullname" . }}-zabbix-proxy-mysql
