apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ template "fullname" . }}-zabbix-proxy-mysql
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    tier: proxy
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}-zabbix-proxy-mysql
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: {{ template "fullname" . }}-zabbix-proxy-mysql
          image: zabbix/zabbix-proxy-mysql:alpine-3.4-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 10051
            protocol: TCP
            name: {{ template "fullname" . }}-zabbix-trapper
          env:
          - name: MYSQL_USER
            valueFrom:
             secretKeyRef:
              name: {{ template "fullname" . }}-db-secret
              key: db-zbx-user
          - name: MYSQL_PASSWORD
            valueFrom:
             secretKeyRef:
              name: {{ template "fullname" . }}-db-secret
              key: db-zbx-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
              name: {{ template "fullname" . }}-db-secret
              key: db-root-pass
          - name: MYSQL_DATABASE
            value: "zabbix_proxy"
