apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" .}}-mysql-server
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    tier: db
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: {{ template "fullname" . }}-mysql-server
  selector:
    name: {{ template "fullname" . }}-mysql-server
