apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ template "fullname" . }}-zabbix-proxy-sqlite3
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    tier: proxy
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}-zabbix-proxy-sqlite3
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: {{ template "fullname" . }}-zabbix-proxy-sqlite3
          image: zabbix/zabbix-proxy-sqlite3:alpine-3.4-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 10051
            protocol: TCP
            name: {{ template "fullname" . }}-zabbix-trapper
          env:
          - name: ZBX_HOSTNAME
            value: "zabbix-proxy-passive"
          - name: ZBX_CONFIGFREQUENCY
            value: "60"
          - name: ZBX_PROXYMODE
            value: "1"
